<?php

/*
|--------------------------------------------------------------------------
| Product Inventory History
|--------------------------------------------------------------------------
| Displays generated and locked business day inventory history.
|--------------------------------------------------------------------------
*/

require_once '../../../includes/config.php';
require_once '../../../includes/connection.php';
require_once '../../../includes/session.php';
require_once '../../../includes/no_cache.php';
require_once '../../../includes/functions.php';
require_once '../../../includes/flash.php';
require_once '../../../includes/auth.php';
require_once '../../../includes/store_permission.php';

requireLogin();
requireRole('accounting');

/*
|--------------------------------------------------------------------------
| Store Permission
|--------------------------------------------------------------------------
*/

$assignedStores = getAccessibleStoreIds($conn);
$storeFilter = buildStoreWhereClause(
    $assignedStores,
    'h.location_id'
);

/*
|--------------------------------------------------------------------------
| Load Inventory History
|--------------------------------------------------------------------------
*/

$sql = "
SELECT
    h.inventory_header_id,
    h.business_date,
    h.business_status,
    h.submitted_at,
    h.generated_at,
    l.location_name,
    u1.full_name AS submitted_by,
    u2.full_name AS generated_by
FROM product_inventory_header h
INNER JOIN locations l
    ON l.location_id = h.location_id
LEFT JOIN users u1
    ON u1.user_id = h.submitted_by
LEFT JOIN users u2
    ON u2.user_id = h.generated_by
WHERE
    h.business_status IN
    (
        'verified',
        'generated',
        'locked'
    )
{$storeFilter}
ORDER BY
    h.business_date DESC,
    l.location_name ASC
";
$result = $conn->query($sql);

/*
|--------------------------------------------------------------------------
| Page Settings
|--------------------------------------------------------------------------
*/

$pageTitle = "Product Inventory History";
$breadcrumbs = [
    [
        'title' => 'Product Inventory',
        'link'  => 'index.php'
    ],
    [
        'title' => 'History'
    ]
];

include '../../../includes/layout/header.php';
include '../../../includes/layout/sidebar.php';
include '../../../includes/layout/topbar.php';
include '../../../includes/layout/breadcrumb.php';

?>

<div class="main-content">
    <div class="container-fluid">
        <?php showFlash(); ?>
        <!-- ==========================================================
        Inventory History
        ========================================================== -->
        <div class="card shadow-sm">
            <div class="card-header bg-white d-flex justify-content-between align-items-center">
                <div>
                    <h5 class="mb-0">Product Inventory History</h5>
                    <small class="text-muted">Displays all Generated and Locked Business Days for your assigned stores.</small>
           </div>
            <a href="index.php" class="btn btn-primary"><i class="bi bi-arrow-left-circle"></i>&nbsp;Back to Inventory</a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered table-hover align-middle" id="historyTable2">
                    <thead class="table-light">
                        <tr>
                            <th width="120">Business Date</th>
                            <th>Store</th>
                            <th width="180">Submitted By</th>
                            <th width="170">Submitted At</th>
                            <th width="180">Generated By</th>
                            <th width="170">Generated At</th>
                            <th width="120">Status</th>
                            <th width="120">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if($result && $result->num_rows > 0): ?>
                            <?php while($row = $result->fetch_assoc()): ?>
                                <tr>
                                    <td><?= date('M d, Y', strtotime($row['business_date'])); ?></td>
                                    <td><?= htmlspecialchars($row['location_name']); ?></td>
                                    <td><?= htmlspecialchars($row['submitted_by'] ?? '-'); ?></td>
                                    <td>
                                        <?= !empty($row['submitted_at'])
                                            ? date('M d, Y h:i A', strtotime($row['submitted_at']))
                                            : '-'; ?>
                                    </td>
                                    <td><?= htmlspecialchars($row['generated_by'] ?? '-'); ?></td>
                                    <td>
                                        <?= !empty($row['generated_at'])
                                            ? date('M d, Y h:i A', strtotime($row['generated_at']))
                                            : '-'; ?>
                                    </td>
                                    <td>
                                        <?php if($row['business_status']=='generated'): ?>
                                            <span class="badge bg-success">Generated</span>
                                        <?php elseif($row['business_status']=='locked'): ?>
                                            <span class="badge bg-dark">Locked</span>
                                        <?php else: ?>
                                            <span class="badge bg-secondary"><?= ucfirst($row['business_status']); ?></span>
                                        <?php endif; ?>
                                    </td>
                                    <td class="text-center"><a href="view.php?id=<?= $row['inventory_header_id']; ?>" class="btn btn-sm btn-primary"><i class="bi bi-eye-fill"></i>&nbsp;View</a></td>
                                </tr>
                            <?php endwhile; ?>
                        <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<?php
    include '../../../includes/layout/footer.php';
?>