<?php

/*
|--------------------------------------------------------------------------
| Product Variance History
|--------------------------------------------------------------------------
| Displays generated and locked product variances.
|--------------------------------------------------------------------------
*/

require_once '../../../includes/config.php';
require_once '../../../includes/connection.php';
require_once '../../../includes/session.php';
require_once '../../../includes/no_cache.php';
require_once '../../../includes/functions.php';
require_once '../../../includes/flash.php';
require_once '../../../includes/auth.php';
require_once '../../../includes/store_permission.php';

requireLogin();
requireRole(['accounting','super_admin']);

/*
|--------------------------------------------------------------------------
| Store Permission
|--------------------------------------------------------------------------
*/

$assignedStores = getAccessibleStoreIds($conn);
$storeFilter = buildStoreWhereClause(
    $assignedStores,
    'h.location_id'
);

/*
|--------------------------------------------------------------------------
| Load Variance History
|--------------------------------------------------------------------------
*/

$sql = "
SELECT
    h.inventory_header_id,
    h.business_date,
    h.business_status,
    h.generated_at,
    h.locked_at,
    l.location_name,
    generator.full_name AS generated_by,
    locker.full_name AS locked_by,
    COUNT(d.inventory_detail_id) AS total_products,
    SUM(
        ABS(d.variance_qty)
    ) AS total_variance
FROM product_inventory_header h
INNER JOIN locations l
    ON l.location_id=h.location_id
LEFT JOIN users generator
    ON generator.user_id=h.generated_by
LEFT JOIN users locker
    ON locker.user_id=h.locked_by
LEFT JOIN product_inventory_details d
    ON d.inventory_header_id=h.inventory_header_id
WHERE
    h.business_status IN
    (
        'generated',
        'locked'
    )
{$storeFilter}
GROUP BY
    h.inventory_header_id
ORDER BY
    h.business_date DESC,
    l.location_name ASC
";
$result = $conn->query($sql);

/*
|--------------------------------------------------------------------------
| Page
|--------------------------------------------------------------------------
*/

$pageTitle = "Variance History";
$breadcrumbs = [
    [
        'title'=>'Product Variance',
        'link'=>'index.php'
    ],
    [
        'title'=>'History'
    ]
];

include '../../../includes/layout/header.php';
include '../../../includes/layout/sidebar.php';
include '../../../includes/layout/topbar.php';
include '../../../includes/layout/breadcrumb.php';

?>

<div class="main-content">
    <div class="container-fluid">
        <?php showFlash(); ?>
        <div class="card shadow-sm">
            <div class="card-header bg-white d-flex justify-content-between align-items-center">
                <div>
                    <h5 class="mb-0">Variance History</h5>
                    <small class="text-muted">Previously generated and locked product variances.</small>
                </div>
            <div>
                <a href="index.php" class="btn btn-primary"><i class="bi bi-arrow-left-circle"></i>&nbsp;Back</a>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table id="varianceHistoryTable" class="table table-bordered table-hover align-middle">
                    <thead>
                        <tr>
                            <th>Business Date</th>
                            <th>Store</th>
                            <th class="text-center">Products</th>
                            <th class="text-end">Variance Qty</th>
                            <th>Generated By</th>
                            <th>Status</th>
                            <th width="150">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php while($row = $result->fetch_assoc()): ?>
                            <?php
                                $statusBadge = 'secondary';
                                switch ($row['business_status']) {
                                    case 'generated':
                                        $statusBadge = 'success';
                                        break;
                                    case 'locked':
                                        $statusBadge = 'dark';
                                        break;
                                    default:
                                        $statusBadge = 'secondary';
                                        break;
                                }
                                $totalVariance = (float)($row['total_variance'] ?? 0);
                            ?>
                            <tr>
                                <td><?= date('M d, Y', strtotime($row['business_date'])); ?></td>
                                <td><?= htmlspecialchars($row['location_name']); ?></td>
                                <td class="text-center"><?= number_format($row['total_products']); ?></td>
                                <td class="text-end"><strong><?= number_format($totalVariance,2); ?></strong></td>
                                <td>
                                    <?= htmlspecialchars($row['generated_by'] ?? '-'); ?>
                                    <?php if(!empty($row['generated_at'])): ?>
                                        <br>
                                        <small class="text-muted"><?= date('M d, Y h:i A', strtotime($row['generated_at'])); ?></small>
                                    <?php endif; ?>
                                </td>
                                <td>
                                    <span class="badge bg-<?= $statusBadge; ?>"><?= ucfirst($row['business_status']); ?></span>
                                    <?php if($row['business_status']=='locked' && !empty($row['locked_by'])): ?>
                                        <br>
                                        <small class="text-muted">Locked by<?= htmlspecialchars($row['locked_by']); ?></small>
                                    <?php endif; ?>
                                </td>
                                <td class="text-center">
                                    <a href="view.php?id=<?= $row['inventory_header_id']; ?>" class="btn btn-sm btn-primary" title="View Variance"><i class="bi bi-eye-fill"></i></a>
                                    <?php if($row['business_status']=='generated'): ?>
                                        <form action="lock.php" method="POST" class="d-inline" onsubmit="return confirm('Lock this Business Day? This action cannot be undone.');">
                                            <input type="hidden" name="inventory_header_id" value="<?= $row['inventory_header_id']; ?>">
                                            <button type="submit" class="btn btn-sm btn-dark" title="Lock Business Day">
                                                <i class="bi bi-lock-fill"></i>
                                            </button>
                                        </form>
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <?php endwhile; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<?php
    include '../../../includes/layout/footer.php';
?>